"""Invoices

Revision ID: 749eecb89542
Revises: 
Create Date: 2025-03-19 13:24:25.782512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749eecb89542'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('external_id', sa.String(), nullable=False),
                    sa.Column('invoice_number', sa.String(), nullable=False),
                    sa.Column('invoice_date', sa.Date(), nullable=False),
                    sa.Column('due_date', sa.Date(), nullable=True),
                    sa.Column('total_amount', sa.Float(), nullable=False),
                    sa.Column('currency', sa.String(), nullable=False),
                    sa.Column('status', sa.Integer(), nullable=False),
                    sa.Column('original_data', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_invoice_external_id'),
                    'invoice', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_external_id'), table_name='invoice')
    op.drop_table('invoice')
    # ### end Alembic commands ###
