"""status_change_date in Service Period

Revision ID: 6a7a4b945f30
Revises: 7536b7d1b92e
Create Date: 2025-04-23 16:38:09.971549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a7a4b945f30'
down_revision: Union[str, None] = '7536b7d1b92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serviceperiod', sa.Column('status_change_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serviceperiod', 'status_change_date')
    # ### end Alembic commands ###
