"""Clients

Revision ID: 002e53430f02
Revises: 749eecb89542
Create Date: 2025-03-20 21:34:12.678062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '002e53430f02'
down_revision: Union[str, None] = '749eecb89542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('encrypted_identifier',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_client_encrypted_identifier'),
                    'client', ['encrypted_identifier'], unique=False)
    op.create_table('clientexternalid',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('client_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('encrypted_external_id',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['client_id'], ['client.id'], name='fk_clientexternalid_client_id'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_clientexternalid_system'),
                    'clientexternalid', ['system'], unique=False)
    op.add_column('invoice', sa.Column(
        'client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_invoice_client_id',
        'invoice', 'client',
        ['client_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_invoice_client_id', 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'client_id')
    op.drop_index(op.f('ix_clientexternalid_system'),
                  table_name='clientexternalid')
    op.drop_table('clientexternalid')
    op.drop_index(op.f('ix_client_encrypted_identifier'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
