"""add_sync_executions_table

Revision ID: 934af5fcae06
Revises: 20250117170000
Create Date: 2025-09-08 14:00:24.165790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '934af5fcae06'
down_revision: Union[str, None] = '45f8db7dec84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_executions',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('process_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='syncexecutionstatus'), nullable=False),
    sa.Column('steps', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_executions_id'), 'sync_executions', ['id'], unique=False)
    op.create_index(op.f('ix_sync_executions_process_id'), 'sync_executions', ['process_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_sync_executions_process_id'), table_name='sync_executions')
    op.drop_index(op.f('ix_sync_executions_id'), table_name='sync_executions')
    op.drop_table('sync_executions')
    # ### end Alembic commands ###
