"""accruals

Revision ID: 7536b7d1b92e
Revises: 2402093cc68c
Create Date: 2025-04-21 18:55:12.821367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7536b7d1b92e'
down_revision: Union[str, None] = '2402093cc68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the enum type (reusing from services migration)
service_contract_status_enum = "servicecontractstatus"
service_contract_status_enum_values = ['ACTIVE', 'CANCELED']


def create_enum(name: str, values: list):
    """Create an enum type safely."""
    enum = postgresql.ENUM(*values, name=name, create_type=False)
    enum.create(op.get_bind(), checkfirst=True)
    return enum


def upgrade() -> None:
    """Upgrade schema."""
    # Get the enum type (it should already exist from services migration)
    contract_status_enum = postgresql.ENUM(
        *service_contract_status_enum_values,
        name=service_contract_status_enum,
        create_type=False
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accruedperiod',
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('accrual_date', sa.Date(), nullable=False),
                    sa.Column('accrued_amount', sa.Float(), nullable=False),
                    sa.Column('accrual_portion', sa.Float(), nullable=False),
                    sa.Column('status', contract_status_enum, nullable=False),
                    sa.Column('sessions_in_period',
                              sa.Integer(), nullable=False),
                    sa.Column('total_contract_amount',
                              sa.Float(), nullable=False),
                    sa.Column('status_change_date', sa.Date(), nullable=True),
                    sa.Column('contract_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['contract_id'], ['servicecontract.id'],
                        name='fk_accruedperiod_contract_id'
                    ),
                    sa.Column('service_period_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['service_period_id'], ['serviceperiod.id'],
                        name='fk_accruedperiod_service_period_id'
                    ),

                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_accruedperiod_accrual_date'),
                    'accruedperiod', ['accrual_date'], unique=False)
    op.create_index(op.f('ix_accruedperiod_status'),
                    'accruedperiod', ['status'], unique=False)
    op.create_index(op.f('ix_servicecontract_status'),
                    'servicecontract', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servicecontract_status'),
                  table_name='servicecontract')
    op.drop_index(op.f('ix_accruedperiod_status'), table_name='accruedperiod')
    op.drop_index(op.f('ix_accruedperiod_accrual_date'),
                  table_name='accruedperiod')
    op.drop_constraint('fk_accruedperiod_contract_id',
                       'accruedperiod', type_='foreignkey')
    op.drop_constraint('fk_accruedperiod_service_period_id',
                       'accruedperiod', type_='foreignkey')
    op.drop_column('accruedperiod', 'service_period_id')
    op.drop_table('accruedperiod')
    # ### end Alembic commands ###
